//jokes created by ChatGPT 4-o
function generateRandomJoke() {
    const jokes = [
        "Why did the JavaScript developer go broke? Because he didn't know how to 'cache' in!",
        "How do JavaScript developers announce a birthday? By throwing an anonymous function!",
        "Why did the developer add ground beef to his JavaScript code? To make it a 'hamburger helper'!",
        "Why did the JavaScript boxer get disqualified? He kept throwing 'NaN' punches!",
        "How does a JavaScript developer propose? By saying 'I call you… with arguments!'",
        "Why don't JavaScript developers trust elevators? Because they don’t know if they’ll go up or down without a callback!",
        "Why do JavaScript developers prefer JSON over XML? Because they love objects and hate tags!",
        "Why did the JavaScript file fail school? Too many 'undefined' answers!",
        "How does JavaScript start its day? With 'var-y' strong coffee!",
        "Why did JavaScript break up with Java? Because it couldn't handle its types!",
        "How many JavaScript developers does it take to change a lightbulb? None, they just call 'switch'!",
        "Why did the developer use '==' instead of '==='? To keep things 'loose'!",
        "What’s a JavaScript developer’s favorite type of music? 'Heavy Callback Metal'!",
        "Why did the array break up with the string? Because it was too pushy!",
        "How do JavaScript developers listen to music? With 'node.js'!",
        "Why do JavaScript developers prefer fat arrows? They never miss their target.",
        "What’s a JavaScript developer's favorite dance? The 'for loop' shuffle!",
        "Why did the JavaScript developer get stuck in the loop? He didn't 'break' up in time!",
        "Why was the JavaScript function late? Because it was in a 'callback hell'!",
        "Why was the JavaScript developer so calm? He was always 'awaiting'!",
        "Why do JavaScript developers hate math? They can never get their 'NaN' numbers right!",
        "What do JavaScript and English majors have in common? They’re both surrounded by a lot of syntax!",
        "How do JavaScript developers enjoy a sweet treat? With a 'function dessert()'!",
        "Why did the developer bring a ladder to the office? Because JavaScript had too many levels of 'scope'!",
        "Why did the JavaScript variable go on a diet? It had too much 'scope'!",
        "Why did the developer need therapy? Because JavaScript was causing 'undefined behavior'!",
        "What’s the favorite dessert of JavaScript arrays? Slice of pi!",
        "Why do JavaScript developers love nature? They appreciate 'scope' everywhere!",
        "Why don’t JavaScript developers like to play hide-and-seek? They keep getting 'undefined'!",
        "Why was JavaScript bad at relationships? Too many 'closures'!",
        "Why did the JavaScript developer bring a ladder to the office? Because they heard their code had too much 'scope'.",
        "What’s a JavaScript developer’s favorite game? 'Promise-keeping'!",
        "Why did the JavaScript developer quit his job? Because he didn't get a 'raise'.",
        "Why do JavaScript developers make bad detectives? They can never find their variables!",
        "How did the JavaScript developer get over his problems? He used 'this'!",
        "Why did JavaScript get kicked out of school? Too many 'undefined' behaviors!",
        "Why do JavaScript developers hate their jobs? Because every day is full of promises they can’t keep!",
        "Why was the JavaScript function happy? Because it knew how to 'return'!",
        "Why do JavaScript arrays work so well in comedy? Because they’re always popping!",
        "Why don’t JavaScript developers travel? They can’t leave their 'scope'.",
        "How does JavaScript cook a steak? Medium-rare, with a side of 'callbacks'.",
        "What did the JavaScript object say to the JSON string? 'You’re looking very stringified!'",
        "Why don’t JavaScript developers play hide-and-seek? They always 'find' each other.",
        "Why did the developer stay calm in a crash? Because he knew there was a 'try-catch'.",
        "What’s a JavaScript developer’s favorite exercise? 'Map' and 'reduce'!",
        "How do JavaScript developers organize a party? They ‘bind’ it all together!",
        "Why did the function fail at stand-up comedy? No one understood its 'context'.",
        "Why do JavaScript developers keep losing their keys? Because they can’t handle 'closure'!",
        "What’s a JavaScript developer’s least favorite room? The 'callback hell'.",
        "Why don’t JavaScript developers trust each other? Too many loose 'types'."
    ];
    let randomIndex = Math.floor(Math.random() * jokes.length);
    return jokes[randomIndex];
}

module.exports = generateRandomJoke;